apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapRoles: |
    - rolearn: arn:aws:iam::592644168886:role/UdacityFlaskDeployCBKubectlRole
      username: Madhavr
      groups:
        - system:masters
